/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2019-08-27 12:57:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<!-- 뷰포트 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\" initial-scale=\"1\">\r\n");
      out.write("<!-- 스타일시트 참조  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<title>태우형님의 웹사이트</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  background-image: url(image/b.jpg);\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <!-- 네비게이션  -->\r\n");
      out.write(" <nav class=\"navbar navbar-default\">\r\n");
      out.write("  <div class=\"navbar-header\">\r\n");
      out.write("   <button type=\"button\" class=\"navbar-toggle collapsed\" \r\n");
      out.write("    data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("    aria-expaned=\"false\">\r\n");
      out.write("     <span class=\"icon-bar\"></span>\r\n");
      out.write("     <span class=\"icon-bar\"></span>\r\n");
      out.write("     <span class=\"icon-bar\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"main.jsp\"><img src=\"image/logo.png\" width=\"60px\" height=\"25px\"/></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <!-- 로그인 여부에 따라 보여지는게 다르다 -->\r\n");
      out.write(" \t");
 
 		String id = (String)session.getAttribute("userID");            // request에서 id 파라미터를 가져온다
		if(id==null || id.equals("")) {                            // id가 Null 이거나 없을 경우
			response.sendRedirect("login.jsp");    // 로그인 페이지로 리다이렉트 한다.
 	
      out.write("\r\n");
      out.write(" \t<div class=\"collapse navbar-collapse\" id=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("   \t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("    \t<li><a href=\"bbs.jsp\">Learn Model</a></li>\r\n");
      out.write("   \t\t</ul>\r\n");
      out.write("\t \t<ul class=\"nav navbar-nav navbar-right1\">\r\n");
      out.write("\t    <li class=\"dropdown\">\r\n");
      out.write("\t     <a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t      data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("\t      aria-expanded=\"false\">Connect<span class=\"caret\"></span></a>\r\n");
      out.write("\t     <ul class=\"dropdown-menu\">\r\n");
      out.write("\t      <li class=\"active\"><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("\t      <li><a href=\"join.jsp\">sign up</a></li>\r\n");
      out.write("\t     </ul>\r\n");
      out.write("\t    </li>\r\n");
      out.write("\t   </ul>\r\n");
      out.write("\t   </div> \r\n");
      out.write("\t </nav>\r\n");
      out.write(" \t");

 		}else if(session.getAttribute("userID").equals("tw")){
 	
      out.write("\r\n");
      out.write(" \t<div class=\"collapse navbar-collapse\" id=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("   \t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("    \t<li><a href=\"model.jsp\">Learn Model</a></li>\r\n");
      out.write("    \t<li><a href=\"predict.jsp\">Predict</a></li>\r\n");
      out.write("    \t<li><a href=\"EDA.jsp\">EDA</a></li>\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\t</ul>\r\n");
      out.write(" \t \t<ul class=\"nav navbar-nav navbar-right2\">\r\n");
      out.write("\t    <li class=\"dropdown\">\r\n");
      out.write("\t     <a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t      data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("\t      aria-expanded=\"false\">Disconnect<span class=\"caret\"></span></a>\r\n");
      out.write("\t     <ul class=\"dropdown-menu\">\r\n");
      out.write("\t      <li><a href=\"logout.jsp\">Log out</a></li>\r\n");
      out.write("\t     </ul>\r\n");
      out.write("\t    </li>\r\n");
      out.write("\t   </ul>\r\n");
      out.write("\t   </div> \r\n");
      out.write("\t</nav>\r\n");
      out.write(" \t");
 
 		}else{
 	
      out.write("\r\n");
      out.write(" \t\t<script>alert(\"관리자 아이디로 로그인하세요!\");</script>\r\n");
      out.write(" \t");
 
 		}
 	
      out.write("\r\n");
      out.write(" <!-- 애니매이션 담당 JQUERY -->\r\n");
      out.write(" <script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script> \r\n");
      out.write(" <!-- 부트스트랩 JS  -->\r\n");
      out.write(" <script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
