/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2019-08-27 13:00:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modelfit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"euc-kr\">\r\n");
      out.write("<title>모델돌리는 곳</title>\r\n");
      out.write("<style>\r\n");
      out.write("#wrap {\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("\tmargin-right: auto;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("body{ background-color: #8eadbf;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".button span {\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  transition: 0.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button span:after {\r\n");
      out.write("  content: '\\00bb';\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  right: -20px;\r\n");
      out.write("  transition: 0.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button:hover span {\r\n");
      out.write("  padding-right: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button:hover span:after {\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("  right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  width: 30%;\r\n");
      out.write("  margin: 10px 520px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("  padding: 3spx;\r\n");
      out.write("  text-align: middle;\r\n");
      out.write("  border-bottom: 1px solid #ddd;\r\n");
      out.write("  border-top: 1px solid #ddd;\r\n");
      out.write("  width: 45px;\r\n");
      out.write("  height: 50px; \r\n");
      out.write("  background: #133a63;\r\n");
      out.write("  color: white; \r\n");
      out.write("}\r\n");
      out.write("td {\r\n");
      out.write("  padding: 3spx;\r\n");
      out.write("  text-align: middle;\r\n");
      out.write("  border-bottom: 1px solid #ddd;\r\n");
      out.write("  border-top: 1px solid #ddd;\r\n");
      out.write("  width: 60px;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  font-weight: 900;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:hover {background-color:#dfedf2;}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("  background-color: #345166;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 15px 32px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  margin: 5px 3px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  -webkit-transition-duration: 0.4s; /* Safari */\r\n");
      out.write("  transition-duration: 0.4s;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		request.setCharacterEncoding("utf-8");
		String model = request.getParameter("model");
		String parameter = request.getParameter("parameter");
		String set = request.getParameter("set");
		String visualization = request.getParameter("visualization");
		String uploadFile = request.getParameter("uploadFile");
		
		//String radio1 = request.getParameter("radio1");
		//out.println(model + "<p>");
		//out.println(parameter + "<p>");
		//out.println(set + "<p>");
		//out.println(visualization + "<p>");
		//out.println(file + "<p>");
	
      out.write("\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br> <b><font size=\"8\" color=\"#e6eef2\">인적자원 평가 모델 돌리기</font></b> <br>\r\n");
      out.write("\t\t<br> <b><font size=\"5\" color=\"#e6eef2\">약간의 시간이 소요될 수 있습니다...</font></b> <br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<form method=\"post\" action=\"shell.jsp\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th id=\"title\">Model</th>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(model);
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th id=\"title\">Parameter</th>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(parameter);
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th id=\"title\">Ratio</th>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(set);
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th id=\"title\">Visualize</th>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(visualization);
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th id=\"title\">File type</ths>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(uploadFile);
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br> <button class=\"button\" style=\"vertical-align:bottom\"><span>Model Operate</span></button>\r\n");
      out.write("\t\t\t<br> <button class=\"button\" style=\"vertical-align:bottom\"><span>Cancle</span></button>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
