/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2019-08-21 14:31:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class model_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<!-- 뷰포트 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\" initial-scale=\"1\">\r\n");
      out.write("<!-- 스타일시트 참조  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body \r\n");
      out.write("label .upload-file {\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label.upload-file p {\r\n");
      out.write("\twidth: 260px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tborder: 1px solid #555;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbackground: #f7f7f7;\r\n");
      out.write("\ttext-indent: 10px;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("\tpadding: 10px 0;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\ttext-overflow: ellipsis;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label.upload-file .btn {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tbackground-color: #555555;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tcontent: \" \";\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label.upload-file input[type=\"file\"] {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#uploadFile {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<title>태우형님의 웹사이트</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		if (session.getAttribute("userID").equals("tw")) {
	
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("\t\t\t\taria-expaned=\"false\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"main.jsp\">AI의 왕 김태우</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\tid=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li><a href=\"main.jsp\">메인</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"model.jsp\">모델돌리기</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"predict.jsp\">예측하기</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right2\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\">접속끊기<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"logout.jsp\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<form action=\"modelfit.jsp\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"bs-example\" data-example-id=\"split-button-dropdown\"\r\n");
      out.write("\t\t\talign=\"center\">\r\n");
      out.write("\t\t\t<!-- Split button1 -->\r\n");
      out.write("\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t<!-- Button1 -->\r\n");
      out.write("\t\t\t\t<button type=\"button\" style=\"color: gold; background: black\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-danger\">Model Selection</button>\r\n");
      out.write("\t\t\t\t<select name=\"model\" style=\"width: 100px; height: 34px;\">\r\n");
      out.write("\t\t\t\t\t<option value=\"Logit\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" value=\"Logit\">Logit</a></li>\r\n");
      out.write("\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Decision Tree\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" value=\"Decision Tree\">Decision Tree</a></li>\r\n");
      out.write("\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Random Forest\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" value=\"Random Forest\">Random Forest</a></li>\r\n");
      out.write("\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"XGBoost\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" value=\"XGBoost\">XGBoost</a></li>\r\n");
      out.write("\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t<option value=\"CNN\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" value=\"CNN\">CNN</a></li>\r\n");
      out.write("\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"RNN\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" value=\"RNN\">RNN</a></li>\r\n");
      out.write("\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Split button2 -->\r\n");
      out.write("\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t<!-- Button2 -->\r\n");
      out.write("\t\t\t\t<button type=\"button\" style=\"color: gold; background: black\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-danger2\">Parameter</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<select name=\"parameter\" style=\"width: 100px; height: 34px;\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" value=\"Parameter1\"><option\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Parameter1\">Parameter1</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" value=\"Parameter2\"><option\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Parameter2\">Parameter2</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" value=\"Parameter3\"><option\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Parameter3\">Parameter3</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" value=\"Super Parameter\"><option\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Super Parameter\">Super Parameter</a></li>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Split button3 -->\r\n");
      out.write("\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t<!-- Button2 -->\r\n");
      out.write("\t\t\t\t<button type=\"button\" style=\"color: gold; background: black\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-danger3\">TestSet/TrainSet</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<select name=\"set\" style=\"width: 100px; height: 34px;\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" value=\"Test : 0.1 / Train : 0.9\"><option\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Test:0.1 / Train:0.9\">Test : 0.1 / Train : 0.9</option></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" value=\"Test : 0.2 / Train : 0.8\"><option\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Test:0.2 / Train:0.8\">Test : 0.2 / Train : 0.8</option></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" value=\"Test : 0.3 / Train : 0.7\"><option\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Test:0.3 / Train:0.7\">Test : 0.3 / Train : 0.7</option></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" value=\"Test : 0.4 / Train : 0.6\"><option\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Test:0.4 / Train:0.6\">Test : 0.4 / Train : 0.6</option></a></li>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Split button4 -->\r\n");
      out.write("\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t<!-- Button2 -->\r\n");
      out.write("\t\t\t\t<button type=\"button\" style=\"color: gold; background: black\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-danger4\">Visualization</button>\r\n");
      out.write("\t\t\t\t<select name=\"visualization\" style=\"width: 100px; height: 34px;\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" value=\"Heatmap\"><option value=\"Heatmap\">Heatmap</option></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" value=\"Graph\"><option value=\"Graph\">Graph</option></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" value=\"Feature Importance\"><option\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Feature Importance\">Feature Importance</option></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" value=\"EDA\"><option value=\"EDA\">EDA</option></a></li>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<!-- Split button5 -->\r\n");
      out.write("\t\t<div class=\"out\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<label for=\"uploadFile\" class=\"upload-file\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn\" style=\"color: gold; background: black\">\r\n");
      out.write("\t\t\t\t\t\t파일찾기<input id=\"uploadFile\" name=\"uploadFile\" type=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\taccept=\"image/*\">\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<p>Click Me!</p> <!-- 업로드파일명 -->\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<br> <span style=\"float: right\"><input type=\"submit\"\r\n");
      out.write("\t\t\tstyle=\"height: 50px; width: 100px;\" value=\"learn model!\"> </span>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
