/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2019-08-21 14:15:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>테스트 페이지</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body \r\n");
      out.write("label .upload-file {\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label.upload-file p {\r\n");
      out.write("\twidth: 260px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tborder: 1px solid #555;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbackground: #f7f7f7;\r\n");
      out.write("\ttext-indent: 10px;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("\tpadding: 10px 0;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\ttext-overflow: ellipsis;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label.upload-file .btn {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tbackground-color: #555555;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tcontent: \" \";\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label.upload-file input[type=\"file\"] {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tmargin: 10px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".where {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin: 25px 15px;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-family: verdana;\r\n");
      out.write("\tfont-style: italic;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox input[type=\"file\"] {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 1px;\r\n");
      out.write("\theight: 1px;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: -1px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tclip: rect(0, 0, 0, 0);\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox label {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: .5em .75em;\r\n");
      out.write("\tcolor: #999;\r\n");
      out.write("\tfont-size: inherit;\r\n");
      out.write("\tline-height: normal;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tbackground-color: #fdfdfd;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tborder: 1px solid #ebebeb;\r\n");
      out.write("\tborder-bottom-color: #e2e2e2;\r\n");
      out.write("\tborder-radius: .25em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* named upload */\r\n");
      out.write(".filebox .upload-name {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: .5em .75em;\r\n");
      out.write("\tfont-size: inherit;\r\n");
      out.write("\tfont-family: inherit;\r\n");
      out.write("\tline-height: normal;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tbackground-color: #f5f5f5;\r\n");
      out.write("\tborder: 1px solid #ebebeb;\r\n");
      out.write("\tborder-bottom-color: #e2e2e2;\r\n");
      out.write("\tborder-radius: .25em;\r\n");
      out.write("\t-webkit-appearance: none;\r\n");
      out.write("\t-moz-appearance: none;\r\n");
      out.write("\tappearance: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox.bs3-primary label {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground-color: #337ab7;\r\n");
      out.write("\tborder-color: #2e6da4;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<!-- 최신버전 제이쿼리 -->\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"filebox bs3-primary\">\r\n");
      out.write("\t\t<input class=\"upload-name\" value=\"파일선택\" disabled=\"disabled\"> <label\r\n");
      out.write("\t\t\tfor=\"ex_filename\">업로드</label> <input type=\"file\" id=\"ex_filename\"\r\n");
      out.write("\t\t\tclass=\"upload-hidden\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<input id=\"inp\" type=\"file\" accept=\"image/*\">\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
